/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './app/__root'
import { Route as AuthRouteImport } from './app/auth'
import { Route as ShellRouteImport } from './app/_shell'
import { Route as AuthSignUpRouteImport } from './app/auth/sign-up'
import { Route as AuthSignInRouteImport } from './app/auth/sign-in'
import { Route as AuthLogoutRouteImport } from './app/auth/logout'
import { Route as AuthCallbackRouteImport } from './app/auth/callback'
import { Route as ApiSplatRouteImport } from './app/api.$'
import { Route as ShellBaseRouteImport } from './app/_shell/_base'
import { Route as ShellAdminRouteImport } from './app/_shell/_admin'
import { Route as ShellBaseIndexRouteImport } from './app/_shell/_base/index'
import { Route as ShellAdminSettingsRouteImport } from './app/_shell/_admin/settings'
import { Route as ShellBaseAgentsIndexRouteImport } from './app/_shell/_base/agents/index'
import { Route as ShellBaseSettingsVoicesIndexRouteImport } from './app/_shell/_base/settings/voices/index'
import { Route as ShellBaseSettingsToolsIndexRouteImport } from './app/_shell/_base/settings/tools/index'
import { Route as ShellBaseSettingsKbIndexRouteImport } from './app/_shell/_base/settings/kb/index'
import { Route as ShellBaseSettingsIntegrationsIndexRouteImport } from './app/_shell/_base/settings/integrations/index'
import { Route as ShellBaseDeployPhoneNumberIndexRouteImport } from './app/_shell/_base/deploy/phone-number/index'
import { Route as ShellBaseDeployBatchCallIndexRouteImport } from './app/_shell/_base/deploy/batch-call/index'
import { Route as ShellBaseAgentsAgentIndexRouteImport } from './app/_shell/_base/agents/$agent/index'
import { Route as ShellBaseAgentsAgentWorkflowsIndexRouteImport } from './app/_shell/_base/agents/$agent/workflows/index'
import { Route as ShellBaseAgentsAgentProceduresIndexRouteImport } from './app/_shell/_base/agents/$agent/procedures/index'
import { Route as ShellBaseAgentsAgentMetricsIndexRouteImport } from './app/_shell/_base/agents/$agent/metrics/index'
import { Route as ShellBaseAgentsAgentLogsIndexRouteImport } from './app/_shell/_base/agents/$agent/logs/index'
import { Route as ShellBaseAgentsAgentKbIndexRouteImport } from './app/_shell/_base/agents/$agent/kb/index'
import { Route as ShellBaseAgentsAgentDeployOutboundIndexRouteImport } from './app/_shell/_base/agents/$agent/deploy/outbound/index'
import { Route as ShellBaseAgentsAgentDeployInboundIndexRouteImport } from './app/_shell/_base/agents/$agent/deploy/inbound/index'
import { Route as ShellBaseAgentsAgentDeployChannelsIndexRouteImport } from './app/_shell/_base/agents/$agent/deploy/channels/index'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellRoute = ShellRouteImport.update({
  id: '/_shell',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLogoutRoute = AuthLogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => AuthRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => AuthRoute,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellBaseRoute = ShellBaseRouteImport.update({
  id: '/_base',
  getParentRoute: () => ShellRoute,
} as any)
const ShellAdminRoute = ShellAdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => ShellRoute,
} as any)
const ShellBaseIndexRoute = ShellBaseIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShellBaseRoute,
} as any)
const ShellAdminSettingsRoute = ShellAdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ShellAdminRoute,
} as any)
const ShellBaseAgentsIndexRoute = ShellBaseAgentsIndexRouteImport.update({
  id: '/agents/',
  path: '/agents/',
  getParentRoute: () => ShellBaseRoute,
} as any)
const ShellBaseSettingsVoicesIndexRoute =
  ShellBaseSettingsVoicesIndexRouteImport.update({
    id: '/settings/voices/',
    path: '/settings/voices/',
    getParentRoute: () => ShellBaseRoute,
  } as any)
const ShellBaseSettingsToolsIndexRoute =
  ShellBaseSettingsToolsIndexRouteImport.update({
    id: '/settings/tools/',
    path: '/settings/tools/',
    getParentRoute: () => ShellBaseRoute,
  } as any)
const ShellBaseSettingsKbIndexRoute =
  ShellBaseSettingsKbIndexRouteImport.update({
    id: '/settings/kb/',
    path: '/settings/kb/',
    getParentRoute: () => ShellBaseRoute,
  } as any)
const ShellBaseSettingsIntegrationsIndexRoute =
  ShellBaseSettingsIntegrationsIndexRouteImport.update({
    id: '/settings/integrations/',
    path: '/settings/integrations/',
    getParentRoute: () => ShellBaseRoute,
  } as any)
const ShellBaseDeployPhoneNumberIndexRoute =
  ShellBaseDeployPhoneNumberIndexRouteImport.update({
    id: '/deploy/phone-number/',
    path: '/deploy/phone-number/',
    getParentRoute: () => ShellBaseRoute,
  } as any)
const ShellBaseDeployBatchCallIndexRoute =
  ShellBaseDeployBatchCallIndexRouteImport.update({
    id: '/deploy/batch-call/',
    path: '/deploy/batch-call/',
    getParentRoute: () => ShellBaseRoute,
  } as any)
const ShellBaseAgentsAgentIndexRoute =
  ShellBaseAgentsAgentIndexRouteImport.update({
    id: '/agents/$agent/',
    path: '/agents/$agent/',
    getParentRoute: () => ShellBaseRoute,
  } as any)
const ShellBaseAgentsAgentWorkflowsIndexRoute =
  ShellBaseAgentsAgentWorkflowsIndexRouteImport.update({
    id: '/agents/$agent/workflows/',
    path: '/agents/$agent/workflows/',
    getParentRoute: () => ShellBaseRoute,
  } as any)
const ShellBaseAgentsAgentProceduresIndexRoute =
  ShellBaseAgentsAgentProceduresIndexRouteImport.update({
    id: '/agents/$agent/procedures/',
    path: '/agents/$agent/procedures/',
    getParentRoute: () => ShellBaseRoute,
  } as any)
const ShellBaseAgentsAgentMetricsIndexRoute =
  ShellBaseAgentsAgentMetricsIndexRouteImport.update({
    id: '/agents/$agent/metrics/',
    path: '/agents/$agent/metrics/',
    getParentRoute: () => ShellBaseRoute,
  } as any)
const ShellBaseAgentsAgentLogsIndexRoute =
  ShellBaseAgentsAgentLogsIndexRouteImport.update({
    id: '/agents/$agent/logs/',
    path: '/agents/$agent/logs/',
    getParentRoute: () => ShellBaseRoute,
  } as any)
const ShellBaseAgentsAgentKbIndexRoute =
  ShellBaseAgentsAgentKbIndexRouteImport.update({
    id: '/agents/$agent/kb/',
    path: '/agents/$agent/kb/',
    getParentRoute: () => ShellBaseRoute,
  } as any)
const ShellBaseAgentsAgentDeployOutboundIndexRoute =
  ShellBaseAgentsAgentDeployOutboundIndexRouteImport.update({
    id: '/agents/$agent/deploy/outbound/',
    path: '/agents/$agent/deploy/outbound/',
    getParentRoute: () => ShellBaseRoute,
  } as any)
const ShellBaseAgentsAgentDeployInboundIndexRoute =
  ShellBaseAgentsAgentDeployInboundIndexRouteImport.update({
    id: '/agents/$agent/deploy/inbound/',
    path: '/agents/$agent/deploy/inbound/',
    getParentRoute: () => ShellBaseRoute,
  } as any)
const ShellBaseAgentsAgentDeployChannelsIndexRoute =
  ShellBaseAgentsAgentDeployChannelsIndexRouteImport.update({
    id: '/agents/$agent/deploy/channels/',
    path: '/agents/$agent/deploy/channels/',
    getParentRoute: () => ShellBaseRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof ShellBaseIndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/api/$': typeof ApiSplatRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/logout': typeof AuthLogoutRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/settings': typeof ShellAdminSettingsRoute
  '/agents/': typeof ShellBaseAgentsIndexRoute
  '/agents/$agent/': typeof ShellBaseAgentsAgentIndexRoute
  '/deploy/batch-call/': typeof ShellBaseDeployBatchCallIndexRoute
  '/deploy/phone-number/': typeof ShellBaseDeployPhoneNumberIndexRoute
  '/settings/integrations/': typeof ShellBaseSettingsIntegrationsIndexRoute
  '/settings/kb/': typeof ShellBaseSettingsKbIndexRoute
  '/settings/tools/': typeof ShellBaseSettingsToolsIndexRoute
  '/settings/voices/': typeof ShellBaseSettingsVoicesIndexRoute
  '/agents/$agent/kb/': typeof ShellBaseAgentsAgentKbIndexRoute
  '/agents/$agent/logs/': typeof ShellBaseAgentsAgentLogsIndexRoute
  '/agents/$agent/metrics/': typeof ShellBaseAgentsAgentMetricsIndexRoute
  '/agents/$agent/procedures/': typeof ShellBaseAgentsAgentProceduresIndexRoute
  '/agents/$agent/workflows/': typeof ShellBaseAgentsAgentWorkflowsIndexRoute
  '/agents/$agent/deploy/channels/': typeof ShellBaseAgentsAgentDeployChannelsIndexRoute
  '/agents/$agent/deploy/inbound/': typeof ShellBaseAgentsAgentDeployInboundIndexRoute
  '/agents/$agent/deploy/outbound/': typeof ShellBaseAgentsAgentDeployOutboundIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof ShellBaseIndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/api/$': typeof ApiSplatRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/logout': typeof AuthLogoutRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/settings': typeof ShellAdminSettingsRoute
  '/agents': typeof ShellBaseAgentsIndexRoute
  '/agents/$agent': typeof ShellBaseAgentsAgentIndexRoute
  '/deploy/batch-call': typeof ShellBaseDeployBatchCallIndexRoute
  '/deploy/phone-number': typeof ShellBaseDeployPhoneNumberIndexRoute
  '/settings/integrations': typeof ShellBaseSettingsIntegrationsIndexRoute
  '/settings/kb': typeof ShellBaseSettingsKbIndexRoute
  '/settings/tools': typeof ShellBaseSettingsToolsIndexRoute
  '/settings/voices': typeof ShellBaseSettingsVoicesIndexRoute
  '/agents/$agent/kb': typeof ShellBaseAgentsAgentKbIndexRoute
  '/agents/$agent/logs': typeof ShellBaseAgentsAgentLogsIndexRoute
  '/agents/$agent/metrics': typeof ShellBaseAgentsAgentMetricsIndexRoute
  '/agents/$agent/procedures': typeof ShellBaseAgentsAgentProceduresIndexRoute
  '/agents/$agent/workflows': typeof ShellBaseAgentsAgentWorkflowsIndexRoute
  '/agents/$agent/deploy/channels': typeof ShellBaseAgentsAgentDeployChannelsIndexRoute
  '/agents/$agent/deploy/inbound': typeof ShellBaseAgentsAgentDeployInboundIndexRoute
  '/agents/$agent/deploy/outbound': typeof ShellBaseAgentsAgentDeployOutboundIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_shell': typeof ShellRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/_shell/_admin': typeof ShellAdminRouteWithChildren
  '/_shell/_base': typeof ShellBaseRouteWithChildren
  '/api/$': typeof ApiSplatRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/logout': typeof AuthLogoutRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/_shell/_admin/settings': typeof ShellAdminSettingsRoute
  '/_shell/_base/': typeof ShellBaseIndexRoute
  '/_shell/_base/agents/': typeof ShellBaseAgentsIndexRoute
  '/_shell/_base/agents/$agent/': typeof ShellBaseAgentsAgentIndexRoute
  '/_shell/_base/deploy/batch-call/': typeof ShellBaseDeployBatchCallIndexRoute
  '/_shell/_base/deploy/phone-number/': typeof ShellBaseDeployPhoneNumberIndexRoute
  '/_shell/_base/settings/integrations/': typeof ShellBaseSettingsIntegrationsIndexRoute
  '/_shell/_base/settings/kb/': typeof ShellBaseSettingsKbIndexRoute
  '/_shell/_base/settings/tools/': typeof ShellBaseSettingsToolsIndexRoute
  '/_shell/_base/settings/voices/': typeof ShellBaseSettingsVoicesIndexRoute
  '/_shell/_base/agents/$agent/kb/': typeof ShellBaseAgentsAgentKbIndexRoute
  '/_shell/_base/agents/$agent/logs/': typeof ShellBaseAgentsAgentLogsIndexRoute
  '/_shell/_base/agents/$agent/metrics/': typeof ShellBaseAgentsAgentMetricsIndexRoute
  '/_shell/_base/agents/$agent/procedures/': typeof ShellBaseAgentsAgentProceduresIndexRoute
  '/_shell/_base/agents/$agent/workflows/': typeof ShellBaseAgentsAgentWorkflowsIndexRoute
  '/_shell/_base/agents/$agent/deploy/channels/': typeof ShellBaseAgentsAgentDeployChannelsIndexRoute
  '/_shell/_base/agents/$agent/deploy/inbound/': typeof ShellBaseAgentsAgentDeployInboundIndexRoute
  '/_shell/_base/agents/$agent/deploy/outbound/': typeof ShellBaseAgentsAgentDeployOutboundIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/api/$'
    | '/auth/callback'
    | '/auth/logout'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/settings'
    | '/agents/'
    | '/agents/$agent/'
    | '/deploy/batch-call/'
    | '/deploy/phone-number/'
    | '/settings/integrations/'
    | '/settings/kb/'
    | '/settings/tools/'
    | '/settings/voices/'
    | '/agents/$agent/kb/'
    | '/agents/$agent/logs/'
    | '/agents/$agent/metrics/'
    | '/agents/$agent/procedures/'
    | '/agents/$agent/workflows/'
    | '/agents/$agent/deploy/channels/'
    | '/agents/$agent/deploy/inbound/'
    | '/agents/$agent/deploy/outbound/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/api/$'
    | '/auth/callback'
    | '/auth/logout'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/settings'
    | '/agents'
    | '/agents/$agent'
    | '/deploy/batch-call'
    | '/deploy/phone-number'
    | '/settings/integrations'
    | '/settings/kb'
    | '/settings/tools'
    | '/settings/voices'
    | '/agents/$agent/kb'
    | '/agents/$agent/logs'
    | '/agents/$agent/metrics'
    | '/agents/$agent/procedures'
    | '/agents/$agent/workflows'
    | '/agents/$agent/deploy/channels'
    | '/agents/$agent/deploy/inbound'
    | '/agents/$agent/deploy/outbound'
  id:
    | '__root__'
    | '/_shell'
    | '/auth'
    | '/_shell/_admin'
    | '/_shell/_base'
    | '/api/$'
    | '/auth/callback'
    | '/auth/logout'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/_shell/_admin/settings'
    | '/_shell/_base/'
    | '/_shell/_base/agents/'
    | '/_shell/_base/agents/$agent/'
    | '/_shell/_base/deploy/batch-call/'
    | '/_shell/_base/deploy/phone-number/'
    | '/_shell/_base/settings/integrations/'
    | '/_shell/_base/settings/kb/'
    | '/_shell/_base/settings/tools/'
    | '/_shell/_base/settings/voices/'
    | '/_shell/_base/agents/$agent/kb/'
    | '/_shell/_base/agents/$agent/logs/'
    | '/_shell/_base/agents/$agent/metrics/'
    | '/_shell/_base/agents/$agent/procedures/'
    | '/_shell/_base/agents/$agent/workflows/'
    | '/_shell/_base/agents/$agent/deploy/channels/'
    | '/_shell/_base/agents/$agent/deploy/inbound/'
    | '/_shell/_base/agents/$agent/deploy/outbound/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ShellRoute: typeof ShellRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  ApiSplatRoute: typeof ApiSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell': {
      id: '/_shell'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ShellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sign-up': {
      id: '/auth/sign-up'
      path: '/sign-up'
      fullPath: '/auth/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/sign-in': {
      id: '/auth/sign-in'
      path: '/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/logout': {
      id: '/auth/logout'
      path: '/logout'
      fullPath: '/auth/logout'
      preLoaderRoute: typeof AuthLogoutRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof AuthRoute
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell/_base': {
      id: '/_shell/_base'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ShellBaseRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/_admin': {
      id: '/_shell/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ShellAdminRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/_base/': {
      id: '/_shell/_base/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ShellBaseIndexRouteImport
      parentRoute: typeof ShellBaseRoute
    }
    '/_shell/_admin/settings': {
      id: '/_shell/_admin/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof ShellAdminSettingsRouteImport
      parentRoute: typeof ShellAdminRoute
    }
    '/_shell/_base/agents/': {
      id: '/_shell/_base/agents/'
      path: '/agents'
      fullPath: '/agents/'
      preLoaderRoute: typeof ShellBaseAgentsIndexRouteImport
      parentRoute: typeof ShellBaseRoute
    }
    '/_shell/_base/settings/voices/': {
      id: '/_shell/_base/settings/voices/'
      path: '/settings/voices'
      fullPath: '/settings/voices/'
      preLoaderRoute: typeof ShellBaseSettingsVoicesIndexRouteImport
      parentRoute: typeof ShellBaseRoute
    }
    '/_shell/_base/settings/tools/': {
      id: '/_shell/_base/settings/tools/'
      path: '/settings/tools'
      fullPath: '/settings/tools/'
      preLoaderRoute: typeof ShellBaseSettingsToolsIndexRouteImport
      parentRoute: typeof ShellBaseRoute
    }
    '/_shell/_base/settings/kb/': {
      id: '/_shell/_base/settings/kb/'
      path: '/settings/kb'
      fullPath: '/settings/kb/'
      preLoaderRoute: typeof ShellBaseSettingsKbIndexRouteImport
      parentRoute: typeof ShellBaseRoute
    }
    '/_shell/_base/settings/integrations/': {
      id: '/_shell/_base/settings/integrations/'
      path: '/settings/integrations'
      fullPath: '/settings/integrations/'
      preLoaderRoute: typeof ShellBaseSettingsIntegrationsIndexRouteImport
      parentRoute: typeof ShellBaseRoute
    }
    '/_shell/_base/deploy/phone-number/': {
      id: '/_shell/_base/deploy/phone-number/'
      path: '/deploy/phone-number'
      fullPath: '/deploy/phone-number/'
      preLoaderRoute: typeof ShellBaseDeployPhoneNumberIndexRouteImport
      parentRoute: typeof ShellBaseRoute
    }
    '/_shell/_base/deploy/batch-call/': {
      id: '/_shell/_base/deploy/batch-call/'
      path: '/deploy/batch-call'
      fullPath: '/deploy/batch-call/'
      preLoaderRoute: typeof ShellBaseDeployBatchCallIndexRouteImport
      parentRoute: typeof ShellBaseRoute
    }
    '/_shell/_base/agents/$agent/': {
      id: '/_shell/_base/agents/$agent/'
      path: '/agents/$agent'
      fullPath: '/agents/$agent/'
      preLoaderRoute: typeof ShellBaseAgentsAgentIndexRouteImport
      parentRoute: typeof ShellBaseRoute
    }
    '/_shell/_base/agents/$agent/workflows/': {
      id: '/_shell/_base/agents/$agent/workflows/'
      path: '/agents/$agent/workflows'
      fullPath: '/agents/$agent/workflows/'
      preLoaderRoute: typeof ShellBaseAgentsAgentWorkflowsIndexRouteImport
      parentRoute: typeof ShellBaseRoute
    }
    '/_shell/_base/agents/$agent/procedures/': {
      id: '/_shell/_base/agents/$agent/procedures/'
      path: '/agents/$agent/procedures'
      fullPath: '/agents/$agent/procedures/'
      preLoaderRoute: typeof ShellBaseAgentsAgentProceduresIndexRouteImport
      parentRoute: typeof ShellBaseRoute
    }
    '/_shell/_base/agents/$agent/metrics/': {
      id: '/_shell/_base/agents/$agent/metrics/'
      path: '/agents/$agent/metrics'
      fullPath: '/agents/$agent/metrics/'
      preLoaderRoute: typeof ShellBaseAgentsAgentMetricsIndexRouteImport
      parentRoute: typeof ShellBaseRoute
    }
    '/_shell/_base/agents/$agent/logs/': {
      id: '/_shell/_base/agents/$agent/logs/'
      path: '/agents/$agent/logs'
      fullPath: '/agents/$agent/logs/'
      preLoaderRoute: typeof ShellBaseAgentsAgentLogsIndexRouteImport
      parentRoute: typeof ShellBaseRoute
    }
    '/_shell/_base/agents/$agent/kb/': {
      id: '/_shell/_base/agents/$agent/kb/'
      path: '/agents/$agent/kb'
      fullPath: '/agents/$agent/kb/'
      preLoaderRoute: typeof ShellBaseAgentsAgentKbIndexRouteImport
      parentRoute: typeof ShellBaseRoute
    }
    '/_shell/_base/agents/$agent/deploy/outbound/': {
      id: '/_shell/_base/agents/$agent/deploy/outbound/'
      path: '/agents/$agent/deploy/outbound'
      fullPath: '/agents/$agent/deploy/outbound/'
      preLoaderRoute: typeof ShellBaseAgentsAgentDeployOutboundIndexRouteImport
      parentRoute: typeof ShellBaseRoute
    }
    '/_shell/_base/agents/$agent/deploy/inbound/': {
      id: '/_shell/_base/agents/$agent/deploy/inbound/'
      path: '/agents/$agent/deploy/inbound'
      fullPath: '/agents/$agent/deploy/inbound/'
      preLoaderRoute: typeof ShellBaseAgentsAgentDeployInboundIndexRouteImport
      parentRoute: typeof ShellBaseRoute
    }
    '/_shell/_base/agents/$agent/deploy/channels/': {
      id: '/_shell/_base/agents/$agent/deploy/channels/'
      path: '/agents/$agent/deploy/channels'
      fullPath: '/agents/$agent/deploy/channels/'
      preLoaderRoute: typeof ShellBaseAgentsAgentDeployChannelsIndexRouteImport
      parentRoute: typeof ShellBaseRoute
    }
  }
}

interface ShellAdminRouteChildren {
  ShellAdminSettingsRoute: typeof ShellAdminSettingsRoute
}

const ShellAdminRouteChildren: ShellAdminRouteChildren = {
  ShellAdminSettingsRoute: ShellAdminSettingsRoute,
}

const ShellAdminRouteWithChildren = ShellAdminRoute._addFileChildren(
  ShellAdminRouteChildren,
)

interface ShellBaseRouteChildren {
  ShellBaseIndexRoute: typeof ShellBaseIndexRoute
  ShellBaseAgentsIndexRoute: typeof ShellBaseAgentsIndexRoute
  ShellBaseAgentsAgentIndexRoute: typeof ShellBaseAgentsAgentIndexRoute
  ShellBaseDeployBatchCallIndexRoute: typeof ShellBaseDeployBatchCallIndexRoute
  ShellBaseDeployPhoneNumberIndexRoute: typeof ShellBaseDeployPhoneNumberIndexRoute
  ShellBaseSettingsIntegrationsIndexRoute: typeof ShellBaseSettingsIntegrationsIndexRoute
  ShellBaseSettingsKbIndexRoute: typeof ShellBaseSettingsKbIndexRoute
  ShellBaseSettingsToolsIndexRoute: typeof ShellBaseSettingsToolsIndexRoute
  ShellBaseSettingsVoicesIndexRoute: typeof ShellBaseSettingsVoicesIndexRoute
  ShellBaseAgentsAgentKbIndexRoute: typeof ShellBaseAgentsAgentKbIndexRoute
  ShellBaseAgentsAgentLogsIndexRoute: typeof ShellBaseAgentsAgentLogsIndexRoute
  ShellBaseAgentsAgentMetricsIndexRoute: typeof ShellBaseAgentsAgentMetricsIndexRoute
  ShellBaseAgentsAgentProceduresIndexRoute: typeof ShellBaseAgentsAgentProceduresIndexRoute
  ShellBaseAgentsAgentWorkflowsIndexRoute: typeof ShellBaseAgentsAgentWorkflowsIndexRoute
  ShellBaseAgentsAgentDeployChannelsIndexRoute: typeof ShellBaseAgentsAgentDeployChannelsIndexRoute
  ShellBaseAgentsAgentDeployInboundIndexRoute: typeof ShellBaseAgentsAgentDeployInboundIndexRoute
  ShellBaseAgentsAgentDeployOutboundIndexRoute: typeof ShellBaseAgentsAgentDeployOutboundIndexRoute
}

const ShellBaseRouteChildren: ShellBaseRouteChildren = {
  ShellBaseIndexRoute: ShellBaseIndexRoute,
  ShellBaseAgentsIndexRoute: ShellBaseAgentsIndexRoute,
  ShellBaseAgentsAgentIndexRoute: ShellBaseAgentsAgentIndexRoute,
  ShellBaseDeployBatchCallIndexRoute: ShellBaseDeployBatchCallIndexRoute,
  ShellBaseDeployPhoneNumberIndexRoute: ShellBaseDeployPhoneNumberIndexRoute,
  ShellBaseSettingsIntegrationsIndexRoute:
    ShellBaseSettingsIntegrationsIndexRoute,
  ShellBaseSettingsKbIndexRoute: ShellBaseSettingsKbIndexRoute,
  ShellBaseSettingsToolsIndexRoute: ShellBaseSettingsToolsIndexRoute,
  ShellBaseSettingsVoicesIndexRoute: ShellBaseSettingsVoicesIndexRoute,
  ShellBaseAgentsAgentKbIndexRoute: ShellBaseAgentsAgentKbIndexRoute,
  ShellBaseAgentsAgentLogsIndexRoute: ShellBaseAgentsAgentLogsIndexRoute,
  ShellBaseAgentsAgentMetricsIndexRoute: ShellBaseAgentsAgentMetricsIndexRoute,
  ShellBaseAgentsAgentProceduresIndexRoute:
    ShellBaseAgentsAgentProceduresIndexRoute,
  ShellBaseAgentsAgentWorkflowsIndexRoute:
    ShellBaseAgentsAgentWorkflowsIndexRoute,
  ShellBaseAgentsAgentDeployChannelsIndexRoute:
    ShellBaseAgentsAgentDeployChannelsIndexRoute,
  ShellBaseAgentsAgentDeployInboundIndexRoute:
    ShellBaseAgentsAgentDeployInboundIndexRoute,
  ShellBaseAgentsAgentDeployOutboundIndexRoute:
    ShellBaseAgentsAgentDeployOutboundIndexRoute,
}

const ShellBaseRouteWithChildren = ShellBaseRoute._addFileChildren(
  ShellBaseRouteChildren,
)

interface ShellRouteChildren {
  ShellAdminRoute: typeof ShellAdminRouteWithChildren
  ShellBaseRoute: typeof ShellBaseRouteWithChildren
}

const ShellRouteChildren: ShellRouteChildren = {
  ShellAdminRoute: ShellAdminRouteWithChildren,
  ShellBaseRoute: ShellBaseRouteWithChildren,
}

const ShellRouteWithChildren = ShellRoute._addFileChildren(ShellRouteChildren)

interface AuthRouteChildren {
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthLogoutRoute: typeof AuthLogoutRoute
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthCallbackRoute: AuthCallbackRoute,
  AuthLogoutRoute: AuthLogoutRoute,
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  ShellRoute: ShellRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  ApiSplatRoute: ApiSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
