import {
	Drawer,
	DrawerContent,
	DrawerFooter,
	DrawerHeader,
	DrawerTitle,
	DrawerTrigger,
} from '../drawer'
import { AiRobotixLogo } from '../logo'
import { ChatIteration } from './chat'
import { ChatConversation } from './conversation'
import type { useAi } from './use-ai'

interface ChatDrawerProps extends React.ComponentProps<typeof DrawerTrigger> {
	handler: ReturnType<typeof useAi>
	direction?: React.ComponentProps<typeof Drawer>['direction']
	label?: string
}

export function AiChatDrawer({
	direction = 'top',
	handler,
	label = 'AI Robotix',
	...props
}: ChatDrawerProps) {
	return (
		<Drawer direction={direction}>
			<DrawerTrigger {...props} />
			<DrawerContent className='flex size-full max-h-[90vh]'>
				<DrawerHeader className='flex flex-row items-center space-x-4 border-b px-4 py-2'>
					<AiRobotixLogo className='size-12' />
					<DrawerTitle>{label}</DrawerTitle>
				</DrawerHeader>
				<div className='no-scrollbar mx-auto flex min-h-0 w-[95%] flex-1 overflow-auto'>
					<ChatConversation {...handler} />
				</div>
				<DrawerFooter className='mx-auto w-[95%] px-0'>
					<ChatIteration {...handler} />
					<a
						href='https://www.airobotix.net/ai-notice'
						target='_blank'
						rel='noopener noreferrer'
						className='mt-2 block text-center text-muted-foreground text-xs underline'
					>
						AI responses are generated by a third-party model and may be
						inaccurate. Click here to learn more.
					</a>
				</DrawerFooter>
			</DrawerContent>
		</Drawer>
	)
}
