import {
	Sheet,
	SheetContent,
	SheetFooter,
	SheetHeader,
	SheetTitle,
	SheetTrigger,
} from '../sheet'
import { PromptInputProvider } from '../ai-elements/prompt-input'
import { ChatIteration } from './chat'
import { ChatConversation } from './conversation'
import type { useAi } from './use-ai'
import { AiRobotixLogo } from '../logo'

interface AiChatSheetProps extends React.ComponentProps<typeof SheetTrigger> {
	handler: ReturnType<typeof useAi>
	label?: string
}

export function AiChatSheet({
	handler,
	label = 'AI Robotix',
	...props
}: AiChatSheetProps) {
	return (
		<Sheet>
			<SheetTrigger {...props} />
			<SheetContent className='scrollbar-background flex size-full overflow-hidden'>
				<SheetHeader className='flex flex-row items-center space-x-4 border-b px-4 py-2'>
					<AiRobotixLogo className='size-12' />
					<SheetTitle>{label}</SheetTitle>
				</SheetHeader>
				<div className='mx-auto flex min-h-0 w-[95%] flex-1'>
					<ChatConversation {...handler} />
				</div>
				<SheetFooter className='mx-auto w-[95%] px-0'>
					<ChatIteration {...handler} />
					<a
						href='https://www.airobotix.net/ai-notice'
						target='_blank'
						rel='noopener noreferrer'
						className='mt-4 block text-center text-muted-foreground text-xs underline'
					>
						AI responses are generated by a third-party model and may be
						inaccurate. Click here to learn more.
					</a>
				</SheetFooter>
			</SheetContent>
		</Sheet>
	)
}
