export const MODELS = [
	{
		id: 'google/gemini-3-pro-preview',
		name: 'Gemini 3 Pro',
		chef: 'Google',
		cost: 'MEDIUM',
		chefSlug: 'google',
		providers: ['google'],
	},
	{
		id: 'google/gemini-2.5-pro',
		name: 'Gemini 2.5 Pro',
		chef: 'Google',
		cost: 'LOW',
		chefSlug: 'google',
		providers: ['google'],
	},
	{
		id: 'google/gemini-3-flash',
		name: 'Gemini 3 Flash',
		chef: 'Google',
		cost: 'CHEAP',
		chefSlug: 'google',
		providers: ['google'],
	},
	{
		id: 'openai/gpt-5.4',
		name: 'GPT-5',
		chef: 'OpenAI',
		cost: 'HIGH',
		chefSlug: 'openai',
		providers: ['openai', 'vercel'],
	},
	{
		id: 'openai/gpt-5.4-mini',
		name: 'GPT-5 Mini',
		chef: 'OpenAI',
		cost: 'LOW',
		chefSlug: 'openai',
		providers: ['openai', 'vercel'],
	},
	{
		id: 'openai/gpt-5.4-nano',
		name: 'GPT-5 Nano',
		chef: 'OpenAI',
		cost: 'LOW',
		chefSlug: 'openai',
		providers: ['openai', 'vercel'],
	},
	{
		id: 'anthropic/claude-opus-4.5',
		name: 'Claude 4 Opus',
		chef: 'Anthropic',
		cost: 'EXPENSIVE',
		chefSlug: 'anthropic',
		providers: ['anthropic', 'vercel', 'google', 'amazon-bedrock'],
	},
	{
		id: 'anthropic/claude-sonnet-4.5',
		name: 'Claude 4 Sonnet',
		chef: 'Anthropic',
		cost: 'MEDIUM',
		chefSlug: 'anthropic',
		providers: ['anthropic', 'vercel', 'google', 'amazon-bedrock'],
	},
	{
		id: 'anthropic/claude-haiku-4.5',
		name: 'Claude 4 Haiku',
		chef: 'Anthropic',
		cost: 'LOW',
		chefSlug: 'anthropic',
		providers: ['anthropic', 'vercel', 'google', 'amazon-bedrock'],
	},
] as const

export type Models = (typeof MODELS)[number]['id']
