/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './app/__root'
import { Route as AuthRouteImport } from './app/auth'
import { Route as ShellRouteImport } from './app/_shell'
import { Route as AuthSignInRouteImport } from './app/auth/sign-in'
import { Route as AuthLogoutRouteImport } from './app/auth/logout'
import { Route as AuthCallbackRouteImport } from './app/auth/callback'
import { Route as ApiSplatRouteImport } from './app/api.$'
import { Route as ShellCrewRouteImport } from './app/_shell/_crew'
import { Route as ShellAdminRouteImport } from './app/_shell/_admin'
import { Route as ShellCrewIndexRouteImport } from './app/_shell/_crew/index'
import { Route as ShellAdminSettingsRouteImport } from './app/_shell/_admin/settings'
import { Route as ShellCrewTeamIndexRouteImport } from './app/_shell/_crew/team/index'
import { Route as ShellCrewTasksIndexRouteImport } from './app/_shell/_crew/tasks/index'
import { Route as ShellCrewSettlementsIndexRouteImport } from './app/_shell/_crew/settlements/index'
import { Route as ShellCrewReportsIndexRouteImport } from './app/_shell/_crew/reports/index'
import { Route as ShellCrewLeadsIndexRouteImport } from './app/_shell/_crew/leads/index'
import { Route as ShellCrewEmailsIndexRouteImport } from './app/_shell/_crew/emails/index'
import { Route as ShellCrewDealsIndexRouteImport } from './app/_shell/_crew/deals/index'
import { Route as ShellCrewConversationsIndexRouteImport } from './app/_shell/_crew/conversations/index'
import { Route as ShellCrewContactsIndexRouteImport } from './app/_shell/_crew/contacts/index'
import { Route as ShellCrewCalendarIndexRouteImport } from './app/_shell/_crew/calendar/index'
import { Route as ShellCrewAutomationIndexRouteImport } from './app/_shell/_crew/automation/index'
import { Route as ShellCrewAccountsIndexRouteImport } from './app/_shell/_crew/accounts/index'
import { Route as ShellCrewSettlementsPlanBuilderRouteImport } from './app/_shell/_crew/settlements/plan-builder'
import { Route as ShellCrewSettlementsIntakeRouteImport } from './app/_shell/_crew/settlements/intake'
import { Route as ShellCrewSettlementsEnrollRouteImport } from './app/_shell/_crew/settlements/enroll'
import { Route as ShellCrewSettlementsDraftScheduleRouteImport } from './app/_shell/_crew/settlements/draft-schedule'
import { Route as ShellCrewSettlementsDisbursementScheduleRouteImport } from './app/_shell/_crew/settlements/disbursement-schedule'
import { Route as ShellCrewSettlementsCreditorRelationshipsRouteImport } from './app/_shell/_crew/settlements/creditor-relationships'
import { Route as ShellCrewSettlementsCustomersIndexRouteImport } from './app/_shell/_crew/settlements/customers/index'
import { Route as ShellCrewSettlementsIdIndexRouteImport } from './app/_shell/_crew/settlements/$id/index'
import { Route as ShellCrewSettingsAppearanceIndexRouteImport } from './app/_shell/_crew/settings/appearance/index'
import { Route as ShellCrewLeadsIdIndexRouteImport } from './app/_shell/_crew/leads/$id/index'
import { Route as ShellCrewDealsIdIndexRouteImport } from './app/_shell/_crew/deals/$id/index'
import { Route as ShellCrewContactsIdIndexRouteImport } from './app/_shell/_crew/contacts/$id/index'
import { Route as ShellCrewAccountsIdIndexRouteImport } from './app/_shell/_crew/accounts/$id/index'
import { Route as ShellCrewSettlementsCustomersIdIndexRouteImport } from './app/_shell/_crew/settlements/customers/$id/index'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellRoute = ShellRouteImport.update({
  id: '/_shell',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLogoutRoute = AuthLogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => AuthRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => AuthRoute,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellCrewRoute = ShellCrewRouteImport.update({
  id: '/_crew',
  getParentRoute: () => ShellRoute,
} as any)
const ShellAdminRoute = ShellAdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => ShellRoute,
} as any)
const ShellCrewIndexRoute = ShellCrewIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShellCrewRoute,
} as any)
const ShellAdminSettingsRoute = ShellAdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ShellAdminRoute,
} as any)
const ShellCrewTeamIndexRoute = ShellCrewTeamIndexRouteImport.update({
  id: '/team/',
  path: '/team/',
  getParentRoute: () => ShellCrewRoute,
} as any)
const ShellCrewTasksIndexRoute = ShellCrewTasksIndexRouteImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => ShellCrewRoute,
} as any)
const ShellCrewSettlementsIndexRoute =
  ShellCrewSettlementsIndexRouteImport.update({
    id: '/settlements/',
    path: '/settlements/',
    getParentRoute: () => ShellCrewRoute,
  } as any)
const ShellCrewReportsIndexRoute = ShellCrewReportsIndexRouteImport.update({
  id: '/reports/',
  path: '/reports/',
  getParentRoute: () => ShellCrewRoute,
} as any)
const ShellCrewLeadsIndexRoute = ShellCrewLeadsIndexRouteImport.update({
  id: '/leads/',
  path: '/leads/',
  getParentRoute: () => ShellCrewRoute,
} as any)
const ShellCrewEmailsIndexRoute = ShellCrewEmailsIndexRouteImport.update({
  id: '/emails/',
  path: '/emails/',
  getParentRoute: () => ShellCrewRoute,
} as any)
const ShellCrewDealsIndexRoute = ShellCrewDealsIndexRouteImport.update({
  id: '/deals/',
  path: '/deals/',
  getParentRoute: () => ShellCrewRoute,
} as any)
const ShellCrewConversationsIndexRoute =
  ShellCrewConversationsIndexRouteImport.update({
    id: '/conversations/',
    path: '/conversations/',
    getParentRoute: () => ShellCrewRoute,
  } as any)
const ShellCrewContactsIndexRoute = ShellCrewContactsIndexRouteImport.update({
  id: '/contacts/',
  path: '/contacts/',
  getParentRoute: () => ShellCrewRoute,
} as any)
const ShellCrewCalendarIndexRoute = ShellCrewCalendarIndexRouteImport.update({
  id: '/calendar/',
  path: '/calendar/',
  getParentRoute: () => ShellCrewRoute,
} as any)
const ShellCrewAutomationIndexRoute =
  ShellCrewAutomationIndexRouteImport.update({
    id: '/automation/',
    path: '/automation/',
    getParentRoute: () => ShellCrewRoute,
  } as any)
const ShellCrewAccountsIndexRoute = ShellCrewAccountsIndexRouteImport.update({
  id: '/accounts/',
  path: '/accounts/',
  getParentRoute: () => ShellCrewRoute,
} as any)
const ShellCrewSettlementsPlanBuilderRoute =
  ShellCrewSettlementsPlanBuilderRouteImport.update({
    id: '/settlements/plan-builder',
    path: '/settlements/plan-builder',
    getParentRoute: () => ShellCrewRoute,
  } as any)
const ShellCrewSettlementsIntakeRoute =
  ShellCrewSettlementsIntakeRouteImport.update({
    id: '/settlements/intake',
    path: '/settlements/intake',
    getParentRoute: () => ShellCrewRoute,
  } as any)
const ShellCrewSettlementsEnrollRoute =
  ShellCrewSettlementsEnrollRouteImport.update({
    id: '/settlements/enroll',
    path: '/settlements/enroll',
    getParentRoute: () => ShellCrewRoute,
  } as any)
const ShellCrewSettlementsDraftScheduleRoute =
  ShellCrewSettlementsDraftScheduleRouteImport.update({
    id: '/settlements/draft-schedule',
    path: '/settlements/draft-schedule',
    getParentRoute: () => ShellCrewRoute,
  } as any)
const ShellCrewSettlementsDisbursementScheduleRoute =
  ShellCrewSettlementsDisbursementScheduleRouteImport.update({
    id: '/settlements/disbursement-schedule',
    path: '/settlements/disbursement-schedule',
    getParentRoute: () => ShellCrewRoute,
  } as any)
const ShellCrewSettlementsCreditorRelationshipsRoute =
  ShellCrewSettlementsCreditorRelationshipsRouteImport.update({
    id: '/settlements/creditor-relationships',
    path: '/settlements/creditor-relationships',
    getParentRoute: () => ShellCrewRoute,
  } as any)
const ShellCrewSettlementsCustomersIndexRoute =
  ShellCrewSettlementsCustomersIndexRouteImport.update({
    id: '/settlements/customers/',
    path: '/settlements/customers/',
    getParentRoute: () => ShellCrewRoute,
  } as any)
const ShellCrewSettlementsIdIndexRoute =
  ShellCrewSettlementsIdIndexRouteImport.update({
    id: '/settlements/$id/',
    path: '/settlements/$id/',
    getParentRoute: () => ShellCrewRoute,
  } as any)
const ShellCrewSettingsAppearanceIndexRoute =
  ShellCrewSettingsAppearanceIndexRouteImport.update({
    id: '/settings/appearance/',
    path: '/settings/appearance/',
    getParentRoute: () => ShellCrewRoute,
  } as any)
const ShellCrewLeadsIdIndexRoute = ShellCrewLeadsIdIndexRouteImport.update({
  id: '/leads/$id/',
  path: '/leads/$id/',
  getParentRoute: () => ShellCrewRoute,
} as any)
const ShellCrewDealsIdIndexRoute = ShellCrewDealsIdIndexRouteImport.update({
  id: '/deals/$id/',
  path: '/deals/$id/',
  getParentRoute: () => ShellCrewRoute,
} as any)
const ShellCrewContactsIdIndexRoute =
  ShellCrewContactsIdIndexRouteImport.update({
    id: '/contacts/$id/',
    path: '/contacts/$id/',
    getParentRoute: () => ShellCrewRoute,
  } as any)
const ShellCrewAccountsIdIndexRoute =
  ShellCrewAccountsIdIndexRouteImport.update({
    id: '/accounts/$id/',
    path: '/accounts/$id/',
    getParentRoute: () => ShellCrewRoute,
  } as any)
const ShellCrewSettlementsCustomersIdIndexRoute =
  ShellCrewSettlementsCustomersIdIndexRouteImport.update({
    id: '/settlements/customers/$id/',
    path: '/settlements/customers/$id/',
    getParentRoute: () => ShellCrewRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof ShellCrewIndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/api/$': typeof ApiSplatRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/logout': typeof AuthLogoutRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/settings': typeof ShellAdminSettingsRoute
  '/settlements/creditor-relationships': typeof ShellCrewSettlementsCreditorRelationshipsRoute
  '/settlements/disbursement-schedule': typeof ShellCrewSettlementsDisbursementScheduleRoute
  '/settlements/draft-schedule': typeof ShellCrewSettlementsDraftScheduleRoute
  '/settlements/enroll': typeof ShellCrewSettlementsEnrollRoute
  '/settlements/intake': typeof ShellCrewSettlementsIntakeRoute
  '/settlements/plan-builder': typeof ShellCrewSettlementsPlanBuilderRoute
  '/accounts/': typeof ShellCrewAccountsIndexRoute
  '/automation/': typeof ShellCrewAutomationIndexRoute
  '/calendar/': typeof ShellCrewCalendarIndexRoute
  '/contacts/': typeof ShellCrewContactsIndexRoute
  '/conversations/': typeof ShellCrewConversationsIndexRoute
  '/deals/': typeof ShellCrewDealsIndexRoute
  '/emails/': typeof ShellCrewEmailsIndexRoute
  '/leads/': typeof ShellCrewLeadsIndexRoute
  '/reports/': typeof ShellCrewReportsIndexRoute
  '/settlements/': typeof ShellCrewSettlementsIndexRoute
  '/tasks/': typeof ShellCrewTasksIndexRoute
  '/team/': typeof ShellCrewTeamIndexRoute
  '/accounts/$id/': typeof ShellCrewAccountsIdIndexRoute
  '/contacts/$id/': typeof ShellCrewContactsIdIndexRoute
  '/deals/$id/': typeof ShellCrewDealsIdIndexRoute
  '/leads/$id/': typeof ShellCrewLeadsIdIndexRoute
  '/settings/appearance/': typeof ShellCrewSettingsAppearanceIndexRoute
  '/settlements/$id/': typeof ShellCrewSettlementsIdIndexRoute
  '/settlements/customers/': typeof ShellCrewSettlementsCustomersIndexRoute
  '/settlements/customers/$id/': typeof ShellCrewSettlementsCustomersIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof ShellCrewIndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/api/$': typeof ApiSplatRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/logout': typeof AuthLogoutRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/settings': typeof ShellAdminSettingsRoute
  '/settlements/creditor-relationships': typeof ShellCrewSettlementsCreditorRelationshipsRoute
  '/settlements/disbursement-schedule': typeof ShellCrewSettlementsDisbursementScheduleRoute
  '/settlements/draft-schedule': typeof ShellCrewSettlementsDraftScheduleRoute
  '/settlements/enroll': typeof ShellCrewSettlementsEnrollRoute
  '/settlements/intake': typeof ShellCrewSettlementsIntakeRoute
  '/settlements/plan-builder': typeof ShellCrewSettlementsPlanBuilderRoute
  '/accounts': typeof ShellCrewAccountsIndexRoute
  '/automation': typeof ShellCrewAutomationIndexRoute
  '/calendar': typeof ShellCrewCalendarIndexRoute
  '/contacts': typeof ShellCrewContactsIndexRoute
  '/conversations': typeof ShellCrewConversationsIndexRoute
  '/deals': typeof ShellCrewDealsIndexRoute
  '/emails': typeof ShellCrewEmailsIndexRoute
  '/leads': typeof ShellCrewLeadsIndexRoute
  '/reports': typeof ShellCrewReportsIndexRoute
  '/settlements': typeof ShellCrewSettlementsIndexRoute
  '/tasks': typeof ShellCrewTasksIndexRoute
  '/team': typeof ShellCrewTeamIndexRoute
  '/accounts/$id': typeof ShellCrewAccountsIdIndexRoute
  '/contacts/$id': typeof ShellCrewContactsIdIndexRoute
  '/deals/$id': typeof ShellCrewDealsIdIndexRoute
  '/leads/$id': typeof ShellCrewLeadsIdIndexRoute
  '/settings/appearance': typeof ShellCrewSettingsAppearanceIndexRoute
  '/settlements/$id': typeof ShellCrewSettlementsIdIndexRoute
  '/settlements/customers': typeof ShellCrewSettlementsCustomersIndexRoute
  '/settlements/customers/$id': typeof ShellCrewSettlementsCustomersIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_shell': typeof ShellRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/_shell/_admin': typeof ShellAdminRouteWithChildren
  '/_shell/_crew': typeof ShellCrewRouteWithChildren
  '/api/$': typeof ApiSplatRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/logout': typeof AuthLogoutRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/_shell/_admin/settings': typeof ShellAdminSettingsRoute
  '/_shell/_crew/': typeof ShellCrewIndexRoute
  '/_shell/_crew/settlements/creditor-relationships': typeof ShellCrewSettlementsCreditorRelationshipsRoute
  '/_shell/_crew/settlements/disbursement-schedule': typeof ShellCrewSettlementsDisbursementScheduleRoute
  '/_shell/_crew/settlements/draft-schedule': typeof ShellCrewSettlementsDraftScheduleRoute
  '/_shell/_crew/settlements/enroll': typeof ShellCrewSettlementsEnrollRoute
  '/_shell/_crew/settlements/intake': typeof ShellCrewSettlementsIntakeRoute
  '/_shell/_crew/settlements/plan-builder': typeof ShellCrewSettlementsPlanBuilderRoute
  '/_shell/_crew/accounts/': typeof ShellCrewAccountsIndexRoute
  '/_shell/_crew/automation/': typeof ShellCrewAutomationIndexRoute
  '/_shell/_crew/calendar/': typeof ShellCrewCalendarIndexRoute
  '/_shell/_crew/contacts/': typeof ShellCrewContactsIndexRoute
  '/_shell/_crew/conversations/': typeof ShellCrewConversationsIndexRoute
  '/_shell/_crew/deals/': typeof ShellCrewDealsIndexRoute
  '/_shell/_crew/emails/': typeof ShellCrewEmailsIndexRoute
  '/_shell/_crew/leads/': typeof ShellCrewLeadsIndexRoute
  '/_shell/_crew/reports/': typeof ShellCrewReportsIndexRoute
  '/_shell/_crew/settlements/': typeof ShellCrewSettlementsIndexRoute
  '/_shell/_crew/tasks/': typeof ShellCrewTasksIndexRoute
  '/_shell/_crew/team/': typeof ShellCrewTeamIndexRoute
  '/_shell/_crew/accounts/$id/': typeof ShellCrewAccountsIdIndexRoute
  '/_shell/_crew/contacts/$id/': typeof ShellCrewContactsIdIndexRoute
  '/_shell/_crew/deals/$id/': typeof ShellCrewDealsIdIndexRoute
  '/_shell/_crew/leads/$id/': typeof ShellCrewLeadsIdIndexRoute
  '/_shell/_crew/settings/appearance/': typeof ShellCrewSettingsAppearanceIndexRoute
  '/_shell/_crew/settlements/$id/': typeof ShellCrewSettlementsIdIndexRoute
  '/_shell/_crew/settlements/customers/': typeof ShellCrewSettlementsCustomersIndexRoute
  '/_shell/_crew/settlements/customers/$id/': typeof ShellCrewSettlementsCustomersIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/api/$'
    | '/auth/callback'
    | '/auth/logout'
    | '/auth/sign-in'
    | '/settings'
    | '/settlements/creditor-relationships'
    | '/settlements/disbursement-schedule'
    | '/settlements/draft-schedule'
    | '/settlements/enroll'
    | '/settlements/intake'
    | '/settlements/plan-builder'
    | '/accounts/'
    | '/automation/'
    | '/calendar/'
    | '/contacts/'
    | '/conversations/'
    | '/deals/'
    | '/emails/'
    | '/leads/'
    | '/reports/'
    | '/settlements/'
    | '/tasks/'
    | '/team/'
    | '/accounts/$id/'
    | '/contacts/$id/'
    | '/deals/$id/'
    | '/leads/$id/'
    | '/settings/appearance/'
    | '/settlements/$id/'
    | '/settlements/customers/'
    | '/settlements/customers/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/api/$'
    | '/auth/callback'
    | '/auth/logout'
    | '/auth/sign-in'
    | '/settings'
    | '/settlements/creditor-relationships'
    | '/settlements/disbursement-schedule'
    | '/settlements/draft-schedule'
    | '/settlements/enroll'
    | '/settlements/intake'
    | '/settlements/plan-builder'
    | '/accounts'
    | '/automation'
    | '/calendar'
    | '/contacts'
    | '/conversations'
    | '/deals'
    | '/emails'
    | '/leads'
    | '/reports'
    | '/settlements'
    | '/tasks'
    | '/team'
    | '/accounts/$id'
    | '/contacts/$id'
    | '/deals/$id'
    | '/leads/$id'
    | '/settings/appearance'
    | '/settlements/$id'
    | '/settlements/customers'
    | '/settlements/customers/$id'
  id:
    | '__root__'
    | '/_shell'
    | '/auth'
    | '/_shell/_admin'
    | '/_shell/_crew'
    | '/api/$'
    | '/auth/callback'
    | '/auth/logout'
    | '/auth/sign-in'
    | '/_shell/_admin/settings'
    | '/_shell/_crew/'
    | '/_shell/_crew/settlements/creditor-relationships'
    | '/_shell/_crew/settlements/disbursement-schedule'
    | '/_shell/_crew/settlements/draft-schedule'
    | '/_shell/_crew/settlements/enroll'
    | '/_shell/_crew/settlements/intake'
    | '/_shell/_crew/settlements/plan-builder'
    | '/_shell/_crew/accounts/'
    | '/_shell/_crew/automation/'
    | '/_shell/_crew/calendar/'
    | '/_shell/_crew/contacts/'
    | '/_shell/_crew/conversations/'
    | '/_shell/_crew/deals/'
    | '/_shell/_crew/emails/'
    | '/_shell/_crew/leads/'
    | '/_shell/_crew/reports/'
    | '/_shell/_crew/settlements/'
    | '/_shell/_crew/tasks/'
    | '/_shell/_crew/team/'
    | '/_shell/_crew/accounts/$id/'
    | '/_shell/_crew/contacts/$id/'
    | '/_shell/_crew/deals/$id/'
    | '/_shell/_crew/leads/$id/'
    | '/_shell/_crew/settings/appearance/'
    | '/_shell/_crew/settlements/$id/'
    | '/_shell/_crew/settlements/customers/'
    | '/_shell/_crew/settlements/customers/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ShellRoute: typeof ShellRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  ApiSplatRoute: typeof ApiSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell': {
      id: '/_shell'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ShellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sign-in': {
      id: '/auth/sign-in'
      path: '/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/logout': {
      id: '/auth/logout'
      path: '/logout'
      fullPath: '/auth/logout'
      preLoaderRoute: typeof AuthLogoutRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof AuthRoute
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell/_crew': {
      id: '/_shell/_crew'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ShellCrewRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/_admin': {
      id: '/_shell/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ShellAdminRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/_crew/': {
      id: '/_shell/_crew/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ShellCrewIndexRouteImport
      parentRoute: typeof ShellCrewRoute
    }
    '/_shell/_admin/settings': {
      id: '/_shell/_admin/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof ShellAdminSettingsRouteImport
      parentRoute: typeof ShellAdminRoute
    }
    '/_shell/_crew/team/': {
      id: '/_shell/_crew/team/'
      path: '/team'
      fullPath: '/team/'
      preLoaderRoute: typeof ShellCrewTeamIndexRouteImport
      parentRoute: typeof ShellCrewRoute
    }
    '/_shell/_crew/tasks/': {
      id: '/_shell/_crew/tasks/'
      path: '/tasks'
      fullPath: '/tasks/'
      preLoaderRoute: typeof ShellCrewTasksIndexRouteImport
      parentRoute: typeof ShellCrewRoute
    }
    '/_shell/_crew/settlements/': {
      id: '/_shell/_crew/settlements/'
      path: '/settlements'
      fullPath: '/settlements/'
      preLoaderRoute: typeof ShellCrewSettlementsIndexRouteImport
      parentRoute: typeof ShellCrewRoute
    }
    '/_shell/_crew/reports/': {
      id: '/_shell/_crew/reports/'
      path: '/reports'
      fullPath: '/reports/'
      preLoaderRoute: typeof ShellCrewReportsIndexRouteImport
      parentRoute: typeof ShellCrewRoute
    }
    '/_shell/_crew/leads/': {
      id: '/_shell/_crew/leads/'
      path: '/leads'
      fullPath: '/leads/'
      preLoaderRoute: typeof ShellCrewLeadsIndexRouteImport
      parentRoute: typeof ShellCrewRoute
    }
    '/_shell/_crew/emails/': {
      id: '/_shell/_crew/emails/'
      path: '/emails'
      fullPath: '/emails/'
      preLoaderRoute: typeof ShellCrewEmailsIndexRouteImport
      parentRoute: typeof ShellCrewRoute
    }
    '/_shell/_crew/deals/': {
      id: '/_shell/_crew/deals/'
      path: '/deals'
      fullPath: '/deals/'
      preLoaderRoute: typeof ShellCrewDealsIndexRouteImport
      parentRoute: typeof ShellCrewRoute
    }
    '/_shell/_crew/conversations/': {
      id: '/_shell/_crew/conversations/'
      path: '/conversations'
      fullPath: '/conversations/'
      preLoaderRoute: typeof ShellCrewConversationsIndexRouteImport
      parentRoute: typeof ShellCrewRoute
    }
    '/_shell/_crew/contacts/': {
      id: '/_shell/_crew/contacts/'
      path: '/contacts'
      fullPath: '/contacts/'
      preLoaderRoute: typeof ShellCrewContactsIndexRouteImport
      parentRoute: typeof ShellCrewRoute
    }
    '/_shell/_crew/calendar/': {
      id: '/_shell/_crew/calendar/'
      path: '/calendar'
      fullPath: '/calendar/'
      preLoaderRoute: typeof ShellCrewCalendarIndexRouteImport
      parentRoute: typeof ShellCrewRoute
    }
    '/_shell/_crew/automation/': {
      id: '/_shell/_crew/automation/'
      path: '/automation'
      fullPath: '/automation/'
      preLoaderRoute: typeof ShellCrewAutomationIndexRouteImport
      parentRoute: typeof ShellCrewRoute
    }
    '/_shell/_crew/accounts/': {
      id: '/_shell/_crew/accounts/'
      path: '/accounts'
      fullPath: '/accounts/'
      preLoaderRoute: typeof ShellCrewAccountsIndexRouteImport
      parentRoute: typeof ShellCrewRoute
    }
    '/_shell/_crew/settlements/plan-builder': {
      id: '/_shell/_crew/settlements/plan-builder'
      path: '/settlements/plan-builder'
      fullPath: '/settlements/plan-builder'
      preLoaderRoute: typeof ShellCrewSettlementsPlanBuilderRouteImport
      parentRoute: typeof ShellCrewRoute
    }
    '/_shell/_crew/settlements/intake': {
      id: '/_shell/_crew/settlements/intake'
      path: '/settlements/intake'
      fullPath: '/settlements/intake'
      preLoaderRoute: typeof ShellCrewSettlementsIntakeRouteImport
      parentRoute: typeof ShellCrewRoute
    }
    '/_shell/_crew/settlements/enroll': {
      id: '/_shell/_crew/settlements/enroll'
      path: '/settlements/enroll'
      fullPath: '/settlements/enroll'
      preLoaderRoute: typeof ShellCrewSettlementsEnrollRouteImport
      parentRoute: typeof ShellCrewRoute
    }
    '/_shell/_crew/settlements/draft-schedule': {
      id: '/_shell/_crew/settlements/draft-schedule'
      path: '/settlements/draft-schedule'
      fullPath: '/settlements/draft-schedule'
      preLoaderRoute: typeof ShellCrewSettlementsDraftScheduleRouteImport
      parentRoute: typeof ShellCrewRoute
    }
    '/_shell/_crew/settlements/disbursement-schedule': {
      id: '/_shell/_crew/settlements/disbursement-schedule'
      path: '/settlements/disbursement-schedule'
      fullPath: '/settlements/disbursement-schedule'
      preLoaderRoute: typeof ShellCrewSettlementsDisbursementScheduleRouteImport
      parentRoute: typeof ShellCrewRoute
    }
    '/_shell/_crew/settlements/creditor-relationships': {
      id: '/_shell/_crew/settlements/creditor-relationships'
      path: '/settlements/creditor-relationships'
      fullPath: '/settlements/creditor-relationships'
      preLoaderRoute: typeof ShellCrewSettlementsCreditorRelationshipsRouteImport
      parentRoute: typeof ShellCrewRoute
    }
    '/_shell/_crew/settlements/customers/': {
      id: '/_shell/_crew/settlements/customers/'
      path: '/settlements/customers'
      fullPath: '/settlements/customers/'
      preLoaderRoute: typeof ShellCrewSettlementsCustomersIndexRouteImport
      parentRoute: typeof ShellCrewRoute
    }
    '/_shell/_crew/settlements/$id/': {
      id: '/_shell/_crew/settlements/$id/'
      path: '/settlements/$id'
      fullPath: '/settlements/$id/'
      preLoaderRoute: typeof ShellCrewSettlementsIdIndexRouteImport
      parentRoute: typeof ShellCrewRoute
    }
    '/_shell/_crew/settings/appearance/': {
      id: '/_shell/_crew/settings/appearance/'
      path: '/settings/appearance'
      fullPath: '/settings/appearance/'
      preLoaderRoute: typeof ShellCrewSettingsAppearanceIndexRouteImport
      parentRoute: typeof ShellCrewRoute
    }
    '/_shell/_crew/leads/$id/': {
      id: '/_shell/_crew/leads/$id/'
      path: '/leads/$id'
      fullPath: '/leads/$id/'
      preLoaderRoute: typeof ShellCrewLeadsIdIndexRouteImport
      parentRoute: typeof ShellCrewRoute
    }
    '/_shell/_crew/deals/$id/': {
      id: '/_shell/_crew/deals/$id/'
      path: '/deals/$id'
      fullPath: '/deals/$id/'
      preLoaderRoute: typeof ShellCrewDealsIdIndexRouteImport
      parentRoute: typeof ShellCrewRoute
    }
    '/_shell/_crew/contacts/$id/': {
      id: '/_shell/_crew/contacts/$id/'
      path: '/contacts/$id'
      fullPath: '/contacts/$id/'
      preLoaderRoute: typeof ShellCrewContactsIdIndexRouteImport
      parentRoute: typeof ShellCrewRoute
    }
    '/_shell/_crew/accounts/$id/': {
      id: '/_shell/_crew/accounts/$id/'
      path: '/accounts/$id'
      fullPath: '/accounts/$id/'
      preLoaderRoute: typeof ShellCrewAccountsIdIndexRouteImport
      parentRoute: typeof ShellCrewRoute
    }
    '/_shell/_crew/settlements/customers/$id/': {
      id: '/_shell/_crew/settlements/customers/$id/'
      path: '/settlements/customers/$id'
      fullPath: '/settlements/customers/$id/'
      preLoaderRoute: typeof ShellCrewSettlementsCustomersIdIndexRouteImport
      parentRoute: typeof ShellCrewRoute
    }
  }
}

interface ShellAdminRouteChildren {
  ShellAdminSettingsRoute: typeof ShellAdminSettingsRoute
}

const ShellAdminRouteChildren: ShellAdminRouteChildren = {
  ShellAdminSettingsRoute: ShellAdminSettingsRoute,
}

const ShellAdminRouteWithChildren = ShellAdminRoute._addFileChildren(
  ShellAdminRouteChildren,
)

interface ShellCrewRouteChildren {
  ShellCrewIndexRoute: typeof ShellCrewIndexRoute
  ShellCrewSettlementsCreditorRelationshipsRoute: typeof ShellCrewSettlementsCreditorRelationshipsRoute
  ShellCrewSettlementsDisbursementScheduleRoute: typeof ShellCrewSettlementsDisbursementScheduleRoute
  ShellCrewSettlementsDraftScheduleRoute: typeof ShellCrewSettlementsDraftScheduleRoute
  ShellCrewSettlementsEnrollRoute: typeof ShellCrewSettlementsEnrollRoute
  ShellCrewSettlementsIntakeRoute: typeof ShellCrewSettlementsIntakeRoute
  ShellCrewSettlementsPlanBuilderRoute: typeof ShellCrewSettlementsPlanBuilderRoute
  ShellCrewAccountsIndexRoute: typeof ShellCrewAccountsIndexRoute
  ShellCrewAutomationIndexRoute: typeof ShellCrewAutomationIndexRoute
  ShellCrewCalendarIndexRoute: typeof ShellCrewCalendarIndexRoute
  ShellCrewContactsIndexRoute: typeof ShellCrewContactsIndexRoute
  ShellCrewConversationsIndexRoute: typeof ShellCrewConversationsIndexRoute
  ShellCrewDealsIndexRoute: typeof ShellCrewDealsIndexRoute
  ShellCrewEmailsIndexRoute: typeof ShellCrewEmailsIndexRoute
  ShellCrewLeadsIndexRoute: typeof ShellCrewLeadsIndexRoute
  ShellCrewReportsIndexRoute: typeof ShellCrewReportsIndexRoute
  ShellCrewSettlementsIndexRoute: typeof ShellCrewSettlementsIndexRoute
  ShellCrewTasksIndexRoute: typeof ShellCrewTasksIndexRoute
  ShellCrewTeamIndexRoute: typeof ShellCrewTeamIndexRoute
  ShellCrewAccountsIdIndexRoute: typeof ShellCrewAccountsIdIndexRoute
  ShellCrewContactsIdIndexRoute: typeof ShellCrewContactsIdIndexRoute
  ShellCrewDealsIdIndexRoute: typeof ShellCrewDealsIdIndexRoute
  ShellCrewLeadsIdIndexRoute: typeof ShellCrewLeadsIdIndexRoute
  ShellCrewSettingsAppearanceIndexRoute: typeof ShellCrewSettingsAppearanceIndexRoute
  ShellCrewSettlementsIdIndexRoute: typeof ShellCrewSettlementsIdIndexRoute
  ShellCrewSettlementsCustomersIndexRoute: typeof ShellCrewSettlementsCustomersIndexRoute
  ShellCrewSettlementsCustomersIdIndexRoute: typeof ShellCrewSettlementsCustomersIdIndexRoute
}

const ShellCrewRouteChildren: ShellCrewRouteChildren = {
  ShellCrewIndexRoute: ShellCrewIndexRoute,
  ShellCrewSettlementsCreditorRelationshipsRoute:
    ShellCrewSettlementsCreditorRelationshipsRoute,
  ShellCrewSettlementsDisbursementScheduleRoute:
    ShellCrewSettlementsDisbursementScheduleRoute,
  ShellCrewSettlementsDraftScheduleRoute:
    ShellCrewSettlementsDraftScheduleRoute,
  ShellCrewSettlementsEnrollRoute: ShellCrewSettlementsEnrollRoute,
  ShellCrewSettlementsIntakeRoute: ShellCrewSettlementsIntakeRoute,
  ShellCrewSettlementsPlanBuilderRoute: ShellCrewSettlementsPlanBuilderRoute,
  ShellCrewAccountsIndexRoute: ShellCrewAccountsIndexRoute,
  ShellCrewAutomationIndexRoute: ShellCrewAutomationIndexRoute,
  ShellCrewCalendarIndexRoute: ShellCrewCalendarIndexRoute,
  ShellCrewContactsIndexRoute: ShellCrewContactsIndexRoute,
  ShellCrewConversationsIndexRoute: ShellCrewConversationsIndexRoute,
  ShellCrewDealsIndexRoute: ShellCrewDealsIndexRoute,
  ShellCrewEmailsIndexRoute: ShellCrewEmailsIndexRoute,
  ShellCrewLeadsIndexRoute: ShellCrewLeadsIndexRoute,
  ShellCrewReportsIndexRoute: ShellCrewReportsIndexRoute,
  ShellCrewSettlementsIndexRoute: ShellCrewSettlementsIndexRoute,
  ShellCrewTasksIndexRoute: ShellCrewTasksIndexRoute,
  ShellCrewTeamIndexRoute: ShellCrewTeamIndexRoute,
  ShellCrewAccountsIdIndexRoute: ShellCrewAccountsIdIndexRoute,
  ShellCrewContactsIdIndexRoute: ShellCrewContactsIdIndexRoute,
  ShellCrewDealsIdIndexRoute: ShellCrewDealsIdIndexRoute,
  ShellCrewLeadsIdIndexRoute: ShellCrewLeadsIdIndexRoute,
  ShellCrewSettingsAppearanceIndexRoute: ShellCrewSettingsAppearanceIndexRoute,
  ShellCrewSettlementsIdIndexRoute: ShellCrewSettlementsIdIndexRoute,
  ShellCrewSettlementsCustomersIndexRoute:
    ShellCrewSettlementsCustomersIndexRoute,
  ShellCrewSettlementsCustomersIdIndexRoute:
    ShellCrewSettlementsCustomersIdIndexRoute,
}

const ShellCrewRouteWithChildren = ShellCrewRoute._addFileChildren(
  ShellCrewRouteChildren,
)

interface ShellRouteChildren {
  ShellAdminRoute: typeof ShellAdminRouteWithChildren
  ShellCrewRoute: typeof ShellCrewRouteWithChildren
}

const ShellRouteChildren: ShellRouteChildren = {
  ShellAdminRoute: ShellAdminRouteWithChildren,
  ShellCrewRoute: ShellCrewRouteWithChildren,
}

const ShellRouteWithChildren = ShellRoute._addFileChildren(ShellRouteChildren)

interface AuthRouteChildren {
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthLogoutRoute: typeof AuthLogoutRoute
  AuthSignInRoute: typeof AuthSignInRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthCallbackRoute: AuthCallbackRoute,
  AuthLogoutRoute: AuthLogoutRoute,
  AuthSignInRoute: AuthSignInRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  ShellRoute: ShellRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  ApiSplatRoute: ApiSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
